### ISSUE TITLE
 AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by shiny4-cyber** [kaguya1st/goats#1]
Traceback (most recent call last):

File "/data/data/com.termux/files/home/Vertus/Vertus
![Screenshot_20240927_215437](https://github.com/user-attachments/assets/5896bea0-feac-46da-8e69-ee0c385981df)
.py", line 442, in <module> main()

File "/data/data/com.termux/files/home/Vertus/Vertus.py", line 416, in main task_ids, task_titles

get_task(token)

File "/data/data/com.termux/files/home/Vertus/Vertus.py", line 186, in get_task recommendations data.get('recommendations {}).get('missions', [])

AttributeError: 'list' object has no attribute 'get'

**Comment by kagushin** [comment]
wait
