### ISSUE TITLE
auto token refresh ?

### ISSUE THREAD

**Issue by supmyhava** [kaguya1st/goats#2]
you can make it to automatic token refresh ?
because everyday we should put the query info again and again

**Comment by kagushin** [comment]
unfortunately bots redeem tokens every day, another option is a bot that uses seasons

**Comment by supmyhava** [comment]
> unfortunately bots redeem tokens every day, another option is a bot that uses seasons

if session can work you can make it?
i dont have a problem with session (:

**Comment by kagushin** [comment]
Using sessions can make Telegram accounts prone to being banned/deleting accounts

**Comment by supmyhava** [comment]
> Using sessions can make Telegram accounts prone to being banned/deleting accounts

Traceback (most recent call last):
  File "/root/goats/main.py", line 11, in <module>
    asyncio.run(main())
  File "/root/.pyenv/versions/3.11.0/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.0/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.0/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/goats/src/core.py", line 375, in main
    await bot.run()
  File "/root/goats/src/core.py", line 308, in run
    user_data = await self.user_data()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/goats/src/core.py", line 100, in user_data
    if not await self.login():
           ^^^^^^^^^^^^^^^^^^
  File "/root/goats/src/core.py", line 91, in login
    access_token = resp_json["tokens"]["access"]["token"]
                   ~~~~~~~~~^^^^^^^^^^
KeyError: 'tokens'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xffffaec05e50>

**Comment by Shinichi29** [comment]
Error bang Goats nya y ?

**Comment by kagushin** [comment]
udah kadaluarsa botnya belom sempet update
